//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shoppingWebsite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class shopping_dataBaseEntities : DbContext
    {
        public shopping_dataBaseEntities()
            : base("name=shopping_dataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<table_admin> table_admin { get; set; }
        public DbSet<table_category> table_category { get; set; }
        public DbSet<table_product> table_product { get; set; }
        public DbSet<table_user> table_user { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
