//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shoppingWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_product
    {
        public int pro_id { get; set; }
        public string pro_name { get; set; }
        public string pro_image { get; set; }
        public string pro_description { get; set; }
        public Nullable<int> pro_price { get; set; }
        public int pro_fk_user { get; set; }
        public int pro_fk_cat { get; set; }
    
        public virtual table_category table_category { get; set; }
        public virtual table_user table_user { get; set; }
    }
}
